---
title: "DA2 CSE3020"
author: "Soham Bhattacharyya 19BCE1199"
date: "11/04/2022"
output: html_document
---

```{r}
df0<-read.csv("LSTM-Multivariate_pollution.csv")
str(df0)
head(df0)
```



```{r pressure}
library(dplyr)
df<-df0
#date<-format(as.POSIXct(df$date),format="%d-%m-%Y")
#cbind(table(date))
df<-df0[as.Date(df0$date)<as.Date("2010-12-12"),]
df$hour<-c(1:nrow(df))
df$wnd_dir<-ifelse(df$wnd_dir=="cv","Static wind",df$wnd_dir)
# df<-df %>%
#   mutate(rain = c(first(rain), diff(rain)),snow=c(first(snow), diff(snow)))
str(df)
```


```{r}
library(ggplot2)
```
```{r}

ggplot(df,aes(hour))+geom_line(aes(y=temp,col="Temperature"))+geom_line(aes(y=dew,col="Dew"))+geom_line(aes(y=press-1000,col="Pressure"))+labs(y="units")
```
```{r}
ggplot(df, aes(press, pollution)) + 
  labs(title="Pressure vs Pollution")+geom_point(aes(fill=wnd_dir,size=wnd_spd),colour="black",pch=21)+labs(x="pressure")
```

```{r}
library(ggcorrplot)
corr <- round(cor(df[2:5]), 1)
ggcorrplot(corr)
```

```{r}
# library(ggcorrplot)
# 
# # Correlation matrix
# 
# corr <- round(cor(df[2:5]), 1)
# 
# # Plot
# ggcorrplot(corr)
library(lattice)
parallelplot(~df[,2:4]|wnd_dir, data = df, layout=c(3,1))
# ggplot(df)+geom_density(aes(x=wnd_spd,fill="Wind speed"),alpha=0.5)+geom_density(aes(x=dew,fill="Dew"),alpha=0.5)+geom_density(aes(x=temp,fill="Temperature"),alpha=0.5)+geom_density(aes(x=press,fill="Pressure"),alpha=0.5)
```


```{r}
library(GGally)

ggpairs(df,columns=2:5)  
```


